### ISSUE TITLE
Error while setting up google_fit platform for sensor

### ISSUE THREAD

**Issue by mr-biz** [IvanVojtko/googlefit-homeassistant#8]
Hi! Thank you for creating Googlefit-HomeAssistant.  I really would like to have Google Fit data for my family in Home Assistant. This allows for automation to be based upon combinations of criteria such as only allowing children Internet access after they have satisfied a number of criteria.  So would like to ask, can Googlefit-HomeAssistant be used for more than one person?
 
The instructions would benefit from some revision to make them more accessible to a less knowledgeable audience.  I have documented my journey and troubleshooting so far.
I have enabled the Google Fit API. How do I "Add all Fitness API read scopes"?
I downloaded a client_secret_...apps.googleusercontent.com.json is that the correct one?
How do I run get_credentials.py?

I created the credentials but HomeAssistant is having errors on startup.

**Comment by mr-biz** [comment]
It seems that the HACS installation did not install get_credentials.py.
So I used a Ubuntu VM to:
git clone https://github.com/IvanVojtko/googlefit-homeassistant.git
sudo apt install python3-pip

Copied the Google Fit credentials to my VM....then...
cp client_secret_blahblahblah.json credentials.json
python3 get_credentials.py

Hey Presto!
I am provided a URL and pasted into browser -> 2OUATH -> Add all Fitness API read scopes.
Now prompted, "Please copy .google_fit.token to your HA configuration directory"

Now back to Home Assistant!

**Comment by mr-biz** [comment]
I copied .google_fit.token to /root/config/custom_components/google_fit

In configuration.yaml I placed:

sensor:
 - platform: google_fit
   name: Google Fit

I restarted Home Assistant and in the logs I got:
 
2022-02-08 18:22:34 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up google_fit platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/google_fit/sensor.py", line 212, in setup_platform
setup(hass, config)
File "/config/custom_components/google_fit/sensor.py", line 146, in setup
return do_authentication(hass, config)
File "/config/custom_components/google_fit/sensor.py", line 160, in do_authentication
client_id=config[CONF_CLIENT_ID],
KeyError: 'client_id'

**Comment by mr-biz** [comment]
![image](https://user-images.githubusercontent.com/44796116/153086917-b45c5eb4-340b-4754-b107-0ebec217a140.png)

**Comment by rpitera** [comment]
> I copied .google_fit.token to /root/config/custom_components/google_fit

I'm having my own issues with installing it and agree about more accessible instructions. But I noticed this line in your thread and the token file should actually be placed in the root of your config directory. - in your case it should be in `/root/config`.

I'm wondering about this token file though; I've used other GFit integrations in the past and they were working fine until recent changes to the API.  But the token files generated look nothing like the one I got as outputted by the get_credentials.py script.  My past token files have been in JSON format, but the one the script generated is definitely NOT JSON formatted.  I can provide a redacted example if it helps the dev out.

**Comment by mr-biz** [comment]
- in your case it should be in `/root/config`.
> 
This appears to have worked for me.  Thank you for the debug!

**Comment by mr-biz** [comment]
> I'm wondering about this token file though; I've used other GFit integrations in the past and they were working fine until recent changes to the API. But the token files generated look nothing like the one I got as outputted by the get_credentials.py script. My past token files have been in JSON format, but the one the script generated is definitely NOT JSON formatted. I can provide a redacted example if it helps the dev out.

Did you take a look at the closed issue? [https://github.com/IvanVojtko/googlefit-homeassistant/issues/6](url)
OP's concern looks similar to your own.

**Comment by rpitera** [comment]
Thanks, but my token is more like the one in issue #7 .  I replied in that thread as well as the reddit topic the dev started.  Hoping to hear something on either front.  I'm glad that I had at least one small victory, even if it wasn't on my setup though!  LOL

**Comment by IvanVojtko** [comment]
Hey @mr-biz and @rpitera. I've updated a readme file. Google changed some stuff in oauth 2 so I updated my script to generate token but also you need to generate a new OAuth 2 credentials and set your device as **Desktop**, otherwise it will not work.

Just go here https://console.cloud.google.com/apis/api/fitness.googleapis.com and click on **Credentials**
![image](https://user-images.githubusercontent.com/3789467/179393814-3f9a8732-9772-4e19-96f2-b6bad9dff5b7.png)
On a next screen click **Create credentials** and select **Oauth client ID**
![image](https://user-images.githubusercontent.com/3789467/179393836-a1cebccc-d740-45ad-8e9d-10d44a511d76.png)
Application type should be **Desktop app** and name whatever you like
![image](https://user-images.githubusercontent.com/3789467/179393859-5277aba3-f83a-451f-9db2-99cab5e11460.png)
Download a JSON file, rename it to `credentials.json`, copy it to the same directory as `get_credentials.py`, run the script. It should automatically open a new tab in a browser. Grant all permissions and you should end up with correct `.google_fit.token` file.
